# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: shoelaces

before:
  hooks:
    - go mod download

builds:
  - id: shoelaces
    main: ./main.go
    binary: shoelaces
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: shoelaces
    ids:
      - shoelaces
    formats:
      - tar.gz
    name_template: shoelaces

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore\\(release\\):"
      - "^docs:"
      - "^test:"

release:
  mode: replace
  footer: |

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
