# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: shoelaces

before:
  hooks:
    - go mod download

builds:
  - id: shoelaces
    main: ./cmd/shoelaces
    binary: shoelaces
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: shoelaces-archives
    ids:
      - shoelaces
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - none*

checksum:
  name_template: checksums.txt

blobs:
  - provider: s3
    region: us-east-2
    bucket: inngest-artifacts
    directory: "shoelaces/releases/{{ .Tag }}"
    ids:
      - shoelaces-archives
    extra_files:
      - glob: ./dist/checksums.txt
    disable: '{{ ne .Env.PUBLISH_S3 "true" }}'
  - provider: s3
    region: us-east-2
    bucket: inngest-artifacts
    directory: "shoelaces/releases/latest"
    ids:
      - shoelaces-archives
    extra_files:
      - glob: ./dist/checksums.txt
    disable: '{{ ne .Env.PUBLISH_S3 "true" }}'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore\\(release\\):"
      - "^docs:"
      - "^test:"

release:
  mode: replace
  footer: |

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
