defaults:
  params:
    encrypt_home: "false"
  boot:
    netboot:
      kernelArgs: []
  repos:
    osMirror: http://ftp.debian.org/debian
    release: trixie
  storage:
    mode: regular
    disk: /dev/nvme0n1
    wipe: true
    wipeDiskPatterns:
      - /dev/nvme*n*

targets:
  debian12:
    script: debian.ipxe
    label: Debian 12 Bookworm (oldstable)
    repos:
      release: bookworm

  debian13:
    script: debian.ipxe
    label: Debian 13 Trixie
    repos:
      release: trixie

  debian13-luks:
    script: debian.ipxe
    label: Debian 13 Trixie LUKS
    repos:
      release: trixie
    storage:
      mode: regular
      encryption:
        enabled: true
        passphrase:
          env: SHOELACES_LUKS_PASSPHRASE

  ubuntu2404:
    script: ubuntu-minimal.ipxe
    label: Ubuntu 24.04 LTS
    repos:
      osMirror: http://mirror.rackspace.com/ubuntu
      release: noble

  ubuntu2604:
    script: ubuntu-minimal.ipxe
    label: Ubuntu 26.04 LTS
    repos:
      osMirror: http://mirror.rackspace.com/ubuntu
      release: resolute

networkMaps:
  - network: 104.225.9.96/27
    defaultTarget: debian13
    targets:
      - debian12
      - debian13
      - debian13-luks
      - ubuntu2404
      - ubuntu2604
    params:
      hostnamePrefix: iad-

  - network: 198.51.100.0/24
    targets:
      - debian12
      - debian13
      - debian13-luks
      - ubuntu2404
      - ubuntu2604

hostnameMaps:
  - hostname: '^debian13-[0-9]+\.example\.com$'
    defaultTarget: debian13
    targets:
      - debian13

  - hostname: '^debian13-luks-[0-9]+\.example\.com$'
    defaultTarget: debian13-luks
    targets:
      - debian13-luks

  - hostname: '^ubuntu24-[0-9]+\.example\.com$'
    defaultTarget: ubuntu2404
    targets:
      - ubuntu2404

macMaps:
  - mac: "0c:42:a1:c3:52:96"
    defaultTarget: ubuntu2604
    targets:
      - ubuntu2604
    network:
      hostname: ubuntu2604-example

ipMaps:
  - ip: 2001:db8::10
    defaultTarget: debian13
    targets:
      - debian12
      - debian13
      - debian13-luks
