networkMaps:
  - network: 104.225.9.96/27
    script:
      name: debian.ipxe
      params:
        release: bookworm
  - network: 198.51.100.0/24
    script:
      name: debian.ipxe
      params:
        release: trixie
hostnameMaps:
  - hostname: msc1.example.com
    script:
      name: ubuntu-minimal.ipxe
      params:
        release: trusty
