networkMaps:
  - network: 104.225.9.96/27
    script:
      name: debian.ipxe
      params:
        release: bookworm
hostnameMaps:
  - hostname: msc1.example.com
    script:
      name: ubuntu-minimal.ipxe
      params:
        release: trusty
