#!/bin/bash

set -euo pipefail

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "${CURRENT_BRANCH}" != "master" && "${CURRENT_BRANCH}" != "release" && "${CURRENT_BRANCH}" != "HEAD" ]]; then
    echo "This script can only be run on the 'master' or 'release' branch."
    exit 1
fi

# Get the latest production release tag and ignore test tags.
LATEST=$(git tag --list 'v[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9][0-9]' --sort=-v:refname | head -n 1)
if [[ -z "${LATEST}" ]]; then
    echo "No production release tag found."
    exit 1
fi

echo "Latest: ${LATEST}"

# Split up the current format into an array using `.` and `-` as the delimiter
IFS='.' read -r -a DEPLOY <<< "${LATEST}"
IFS='-' read -r -a DATE <<< "${DEPLOY[0]}"

YEAR=${DATE[0]}
MONTH=${DATE[1]}
DAY=${DATE[2]}
INDEX=${DEPLOY[1]}
INDEX=$((10#$INDEX))

PREV_DATE="${YEAR}-${MONTH}-${DAY}"

# NOTE: For debugging
echo "Year: ${YEAR}, Month: ${MONTH}, Index: ${INDEX}"

CURRENT_YEAR=$(date -u +'%Y')
CURRENT_MONTH=$(date -u +'%m')
CURRENT_DAY=$(date -u +'%d')

NEXT="v${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DAY}"

# If the day is different from the latest one
# that means we need to start a new tag with the current day
if [[ "${PREV_DATE}" != "${NEXT}" ]]; then
    NEXT="${NEXT}.01"
else
    # if current month is the same as the latest,
    # bump the index
    NEW_INDEX=$((${INDEX}+1))
    NEXT="${NEXT}.$(printf "%02d" "$NEW_INDEX")"
fi

echo "Next tag: ${NEXT}"

# Tag the repository with the new deployment tag.
# GitHub actions will then deploy the tag.
git tag ${NEXT} # && git push origin ${NEXT}
