// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boot_sessions.sql

package sqlitedb

import (
	"context"
)

const createBootSession = `-- name: CreateBootSession :exec
INSERT INTO boot_sessions (
  ref,
  mac,
  ip,
  hostname,
  target,
  environment,
  params_json,
  users_json,
  provisioning_json,
  created_at_unix_nano,
  expires_at_unix_nano
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBootSessionParams struct {
	Ref               string `json:"ref"`
	Mac               string `json:"mac"`
	Ip                string `json:"ip"`
	Hostname          string `json:"hostname"`
	Target            string `json:"target"`
	Environment       string `json:"environment"`
	ParamsJson        []byte `json:"params_json"`
	UsersJson         []byte `json:"users_json"`
	ProvisioningJson  []byte `json:"provisioning_json"`
	CreatedAtUnixNano int64  `json:"created_at_unix_nano"`
	ExpiresAtUnixNano int64  `json:"expires_at_unix_nano"`
}

func (q *Queries) CreateBootSession(ctx context.Context, arg CreateBootSessionParams) error {
	_, err := q.db.ExecContext(ctx, createBootSession,
		arg.Ref,
		arg.Mac,
		arg.Ip,
		arg.Hostname,
		arg.Target,
		arg.Environment,
		arg.ParamsJson,
		arg.UsersJson,
		arg.ProvisioningJson,
		arg.CreatedAtUnixNano,
		arg.ExpiresAtUnixNano,
	)
	return err
}

const deleteBootSessionsBefore = `-- name: DeleteBootSessionsBefore :execrows
DELETE FROM boot_sessions
WHERE expires_at_unix_nano < ?
`

func (q *Queries) DeleteBootSessionsBefore(ctx context.Context, expiresAtUnixNano int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBootSessionsBefore, expiresAtUnixNano)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBootSession = `-- name: GetBootSession :one
SELECT
  ref,
  mac,
  ip,
  hostname,
  target,
  environment,
  params_json,
  users_json,
  provisioning_json,
  created_at_unix_nano,
  expires_at_unix_nano
FROM boot_sessions
WHERE ref = ?
  AND expires_at_unix_nano > ?
`

type GetBootSessionParams struct {
	Ref               string `json:"ref"`
	ExpiresAtUnixNano int64  `json:"expires_at_unix_nano"`
}

func (q *Queries) GetBootSession(ctx context.Context, arg GetBootSessionParams) (BootSession, error) {
	row := q.db.QueryRowContext(ctx, getBootSession, arg.Ref, arg.ExpiresAtUnixNano)
	var i BootSession
	err := row.Scan(
		&i.Ref,
		&i.Mac,
		&i.Ip,
		&i.Hostname,
		&i.Target,
		&i.Environment,
		&i.ParamsJson,
		&i.UsersJson,
		&i.ProvisioningJson,
		&i.CreatedAtUnixNano,
		&i.ExpiresAtUnixNano,
	)
	return i, err
}
