// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlitedb

import (
	"context"
)

const deleteEventsBefore = `-- name: DeleteEventsBefore :execrows
DELETE FROM events
WHERE occurred_at_unix_nano < ?
`

func (q *Queries) DeleteEventsBefore(ctx context.Context, occurredAtUnixNano int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventsBefore, occurredAtUnixNano)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
  id,
  event_type,
  occurred_at_unix_nano,
  mac,
  ip,
  hostname,
  boot_type,
  script,
  message,
  params_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertEventParams struct {
	ID                 []byte `json:"id"`
	EventType          int64  `json:"event_type"`
	OccurredAtUnixNano int64  `json:"occurred_at_unix_nano"`
	Mac                string `json:"mac"`
	Ip                 string `json:"ip"`
	Hostname           string `json:"hostname"`
	BootType           string `json:"boot_type"`
	Script             string `json:"script"`
	Message            string `json:"message"`
	ParamsJson         []byte `json:"params_json"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.OccurredAtUnixNano,
		arg.Mac,
		arg.Ip,
		arg.Hostname,
		arg.BootType,
		arg.Script,
		arg.Message,
		arg.ParamsJson,
	)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const listEvents = `-- name: ListEvents :many
SELECT
  id,
  event_type,
  occurred_at_unix_nano,
  mac,
  ip,
  hostname,
  boot_type,
  script,
  message,
  params_json
FROM events
ORDER BY occurred_at_unix_nano ASC, id ASC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.OccurredAtUnixNano,
			&i.Mac,
			&i.Ip,
			&i.Hostname,
			&i.BootType,
			&i.Script,
			&i.Message,
			&i.ParamsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
