// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

type BootSession struct {
	Ref               string `json:"ref"`
	Mac               string `json:"mac"`
	Ip                string `json:"ip"`
	Hostname          string `json:"hostname"`
	Target            string `json:"target"`
	Environment       string `json:"environment"`
	ParamsJson        []byte `json:"params_json"`
	UsersJson         []byte `json:"users_json"`
	ProvisioningJson  []byte `json:"provisioning_json"`
	CreatedAtUnixNano int64  `json:"created_at_unix_nano"`
	ExpiresAtUnixNano int64  `json:"expires_at_unix_nano"`
}

type Event struct {
	ID                 []byte `json:"id"`
	EventType          int64  `json:"event_type"`
	OccurredAtUnixNano int64  `json:"occurred_at_unix_nano"`
	Mac                string `json:"mac"`
	Ip                 string `json:"ip"`
	Hostname           string `json:"hostname"`
	BootType           string `json:"boot_type"`
	Script             string `json:"script"`
	Message            string `json:"message"`
	ParamsJson         []byte `json:"params_json"`
}

type ServerState struct {
	Mac                string `json:"mac"`
	Ip                 string `json:"ip"`
	Hostname           string `json:"hostname"`
	Target             string `json:"target"`
	Environment        string `json:"environment"`
	ParamsJson         []byte `json:"params_json"`
	UsersJson          []byte `json:"users_json"`
	ProvisioningJson   []byte `json:"provisioning_json"`
	AllowedTargetsJson []byte `json:"allowed_targets_json"`
	Retry              int64  `json:"retry"`
	LastAccessUnixNano int64  `json:"last_access_unix_nano"`
}
