// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_states.sql

package sqlitedb

import (
	"context"
)

const deleteServerState = `-- name: DeleteServerState :execrows
DELETE FROM server_states
WHERE mac = ?
`

func (q *Queries) DeleteServerState(ctx context.Context, mac string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServerState, mac)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteServerStatesBefore = `-- name: DeleteServerStatesBefore :execrows
DELETE FROM server_states
WHERE last_access_unix_nano < ?
`

func (q *Queries) DeleteServerStatesBefore(ctx context.Context, lastAccessUnixNano int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServerStatesBefore, lastAccessUnixNano)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getServerState = `-- name: GetServerState :one
SELECT
  mac,
  ip,
  hostname,
  target,
  environment,
  params_json,
  users_json,
  provisioning_json,
  allowed_targets_json,
  retry,
  last_access_unix_nano
FROM server_states
WHERE mac = ?
`

func (q *Queries) GetServerState(ctx context.Context, mac string) (ServerState, error) {
	row := q.db.QueryRowContext(ctx, getServerState, mac)
	var i ServerState
	err := row.Scan(
		&i.Mac,
		&i.Ip,
		&i.Hostname,
		&i.Target,
		&i.Environment,
		&i.ParamsJson,
		&i.UsersJson,
		&i.ProvisioningJson,
		&i.AllowedTargetsJson,
		&i.Retry,
		&i.LastAccessUnixNano,
	)
	return i, err
}

const listServerStates = `-- name: ListServerStates :many
SELECT
  mac,
  ip,
  hostname,
  target,
  environment,
  params_json,
  users_json,
  provisioning_json,
  allowed_targets_json,
  retry,
  last_access_unix_nano
FROM server_states
ORDER BY mac ASC
`

func (q *Queries) ListServerStates(ctx context.Context) ([]ServerState, error) {
	rows, err := q.db.QueryContext(ctx, listServerStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerState
	for rows.Next() {
		var i ServerState
		if err := rows.Scan(
			&i.Mac,
			&i.Ip,
			&i.Hostname,
			&i.Target,
			&i.Environment,
			&i.ParamsJson,
			&i.UsersJson,
			&i.ProvisioningJson,
			&i.AllowedTargetsJson,
			&i.Retry,
			&i.LastAccessUnixNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServerState = `-- name: UpsertServerState :exec
INSERT INTO server_states (
  mac,
  ip,
  hostname,
  target,
  environment,
  params_json,
  users_json,
  provisioning_json,
  allowed_targets_json,
  retry,
  last_access_unix_nano
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(mac) DO UPDATE SET
  ip = excluded.ip,
  hostname = excluded.hostname,
  target = excluded.target,
  environment = excluded.environment,
  params_json = excluded.params_json,
  users_json = excluded.users_json,
  provisioning_json = excluded.provisioning_json,
  allowed_targets_json = excluded.allowed_targets_json,
  retry = excluded.retry,
  last_access_unix_nano = excluded.last_access_unix_nano
`

type UpsertServerStateParams struct {
	Mac                string `json:"mac"`
	Ip                 string `json:"ip"`
	Hostname           string `json:"hostname"`
	Target             string `json:"target"`
	Environment        string `json:"environment"`
	ParamsJson         []byte `json:"params_json"`
	UsersJson          []byte `json:"users_json"`
	ProvisioningJson   []byte `json:"provisioning_json"`
	AllowedTargetsJson []byte `json:"allowed_targets_json"`
	Retry              int64  `json:"retry"`
	LastAccessUnixNano int64  `json:"last_access_unix_nano"`
}

func (q *Queries) UpsertServerState(ctx context.Context, arg UpsertServerStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertServerState,
		arg.Mac,
		arg.Ip,
		arg.Hostname,
		arg.Target,
		arg.Environment,
		arg.ParamsJson,
		arg.UsersJson,
		arg.ProvisioningJson,
		arg.AllowedTargetsJson,
		arg.Retry,
		arg.LastAccessUnixNano,
	)
	return err
}
